#!/usr/bin/env bash
docker run --rm -d --read-only -u $UID:$EUID \
-v $(xdg-user-dir VIDEOS):/target maxpatternman/youtube-dl \
-q -f bestvideo[ext=mp4]+bestaudio[ext=m4a] \
-o "%(title)s.%(ext)s" \
--no-cache-dir $1
